### ISSUE TITLE
`require` other script

### ISSUE THREAD

**Issue by lduboeuf** [fengari-lua/fengari-web#23]
hi,
Awesome work :) . Just curious about the project. can we load another lua script ?
e.g `local myModule = require "myModule"`  ( myModule.lua would be in same path ) ?

**Comment by daurnimator** [comment]
Yes. By default it does a synchronous XHR.

For production usage, it may be a smart idea to pre-load your modules by loading them all in parllel and put them into package.preload or package.loaded

**Comment by lduboeuf** [comment]
ok, maybe i did something wrong with require. it does not work here ( firefox last release). but only tried without a local web server. if you have any examples for package.preload, would benice. ;-)

**Comment by lduboeuf** [comment]
ok, seems to work behind a web server

**Comment by daurnimator** [comment]
What do you mean "does not work"? What can you see in the developer tools network panel?

**Comment by lduboeuf** [comment]
yes, by serving my files with an web server it works fine but not without it.

**Comment by giann** [comment]
Must be a CORS error

**Comment by lduboeuf** [comment]
humm, i don't load any external script.
here is output error:
```
DOMException
code: 19
columnNumber: 0
data: null
filename: "file:///home/lionel/dev/web/testfengari/fengari-web.js"
lineNumber: 8
message: "A network error occurred."
name: "NetworkError
```

**Comment by daurnimator** [comment]
> humm, i don't load any external script.

What do you mean?

> here is output error when trying to require lua script file on same folder

Where do you see this?

What can you see in the network tab?

**Comment by lduboeuf** [comment]
Right, i've put my test project in `https://github.com/lduboeuf/fengari-test`
So by cloning the project and launch `firefox index.html` (without any webserver) it will not work ( see error in console above )
Don't have anything in network tab because i'm not behind a webserver.
Everything is fine if i use a webserver.

**Comment by daurnimator** [comment]
Okay thanks for explaining. Looks like this is a firefox security choice. see e.g. https://stackoverflow.com/questions/192080/firefox-links-to-local-or-network-pages-do-not-work

The solution is to use a web server. A common one for messing around is to just type `python -m http.server` for python 3 or `python -m SimpleHTTPServer` if you only have python 2.

**Comment by lduboeuf** [comment]
humm that is strange, i still can use local XMLHttpRequest on other projects on firefox at least ( i know chrome don't allow it). but that is fine, i will do behing a webserver :).
Would be great to see a complete working example to see all potentials of fengari

**Comment by giann** [comment]
You can take a look at the source of [fengari.io](https://github.com/fengari-lua/fengari.io) which uses itself fengari to implement snippets and the REPL.

**Comment by daurnimator** [comment]
> I still can use local XMLHttpRequest on other projects on firefox at least

Do you have an example of where it's working to do an XHR to a local `file://` url?

**Comment by lduboeuf** [comment]
yes i use it in my offline webapp: https://github.com/lduboeuf/team-tool-box
the xhr is here: https://github.com/lduboeuf/team-tool-box/blob/master/src/vendors/spapp.js#L115

**Comment by daurnimator** [comment]
> yes i use it in my offline webapp: https://github.com/lduboeuf/team-tool-box
> the xhr is here: https://github.com/lduboeuf/team-tool-box/blob/master/src/vendors/spapp.js#L115

I don't see how that is a file:// url though? The repository uses the browser-sync server (which btw is missing from your package.json file)

**Comment by lduboeuf** [comment]
i don't use browser-sync to serve files, ( old code). i do it without web server. just `git clone...` and `firefox src/index.html` and it works

**Comment by jack0088** [comment]
When I try to require another lua script into my current lua file, then I get a strange message popping up. Pease see the image. However when I put that script into a subfolder `./lua/5.3/prettyprint.lua` it works without complaints. Am I supposed to change the search path or something to avoid this error throwing of fengari?

<img width="1658" alt="bildschirmfoto 2018-09-02 um 00 57 33" src="https://user-images.githubusercontent.com/1267980/44950561-3d5bb280-ae4b-11e8-8b12-f71306387aa1.png">

**Comment by daurnimator** [comment]
@jack0088  please don't reuse unrelated issues.

> When I try to require another lua script into my current lua file, then I get a strange message popping up.

See  https://bugs.chromium.org/p/chromium/issues/detail?id=124534#c36

> Am I supposed to change the search path or something to avoid this error throwing of fengari?

You can (edit `package.path` or set the JS global `LUA_PATH`). However better practice would be to preload your dependencies to avoid the synchronous XHR. You can do this yourself by fetching them and saving them into `package.preload` before you run your script. See [fengari-loader](https://github.com/fengari-lua/fengari-loader/) for a webpack loader that does this all for you.
