### ISSUE TITLE
Question: Loading external modules

### ISSUE THREAD

**Issue by lukehedger** [fengari-lua/fengari-web#32]
I have a Lua script that uses an external library (`lua-fun`):
```js
import { lauxlib } from 'fengari-web'

lauxlib.luaL_loadstring(L, to_luastring(`
  require 'fun'()
  return operator.le(1, 2)
`))
```

When I run this code with `fengari` it works fine. But when I run it with `fengari-web` I get an error in the console:
```
GET http://localhost:5000/lua/5.3/fun.lua 404 (Not Found)
GET http://localhost:5000/lua/5.3/fun.js 404 (Not Found)
Uncaught Error: PANIC: unprotected error in call to Lua API ([string "require 'fun'() return operator.le(..."]:1: module 'fun' not found:
```

How can I load an external module when using Fengari in the browser?

**Comment by daurnimator** [comment]
Why are you using `lauxlib` directly?
Using the classic lua C API from JS comes with all the normal caveats of the Lua C API in C: e.g. calls that can throw should be called from inside of a pcall

You probably want to use the `fengari.load(source, chunkname)` helper function that does all of that for you.

> How can I load an external module when using Fengari in the browser?

Where is lua-fun installed/uploaded?

  - Are you hosting it yourself?
  - Or are you bundling it somehow?
  - Or are you wanting to grab it from e.g. github dynamically?

**Comment by daurnimator** [comment]
> Sorry! I'm still picking up the conventions of Lua. What would be a better alternative to lauxlib.luaL_loadstring(L, to_luastring(someLua))?

It's not the `luaL_loadstring` that is the issue; but how you then proceed to call the code (which you haven't shared)

> This looks good! What are the expected values of source and chunkname?

A string (JS string or Lua string) of the source code to run, and the chunk name. Similar to the [traditional `load` function in lua](https://www.lua.org/manual/5.3/manual.html#pdf-load).

> Would the fengari-loader be an alternative to this? (The project uses Webpack)

Yes! :)

> It is stored in the environment the JS application is running in (so, either locally or on a remote server at the path /usr/local/share/lua/5.3/fun.lua)

The client needs to be able to access the code or else it can't run it. You'll need to either serve the code (see the error message for where fengari looks for it by default!), or bundle it (e.g. with webpack)

**Comment by lukehedger** [comment]
> how you then proceed to call the code

Ah, I see! So I call the code with:
```js
lua.lua_call(L, 0, 1)
```

Thanks - I'll give the Webpack loader a go! 😄

**Comment by daurnimator** [comment]
> So I call the code with:
> 
> lua.lua_call(L, 0, 1)

Yeah; to call the code "correctly" you need to call it with `lua_pcall`. If you want tracebacks then you also need to install a message handler.

**Comment by daurnimator** [comment]
> I'll give the Webpack loader a go!

That should be much simpler for you!
Node that you may need to modify your webpack config to tell it where to find your lua modules.

**Comment by lukehedger** [comment]
I now have the following code:
```js
import { load } from 'fengari-web'

load(`
  require 'fun'()
  return operator.le(1, 2)
`)
```

This returns a slightly different error message but, ultimately, `fun.lua` still cannot be found:
```
GET http://localhost:5000/page/lua/5.3/fun.lua 404 (Not Found)
GET http://localhost:5000/page/lua/5.3/fun.js 404 (Not Found)
fengari-web.bundle.js:8 Uncaught [string "?"]:1: module 'fun' not found:
	no field package.preload['fun']
	no file './lua/5.3/fun.lua'
	no file './lua/5.3/fun/init.lua'
	no file './fun.lua'
	no file './fun/init.lua'
	no file './lua/5.3/fun.js'
	no file './lua/5.3/loadall.js'
	no file './fun.js'
```

I have realised the Webpack loader will not work as I am not directly loading any `.lua` files, as my Lua code is generated dynamically at runtime (but always with the `fun` module as a dependency).

Is there a way to define the `LUA_PATH` that `fengari-web` uses to resolve `require` statements (assuming `fun.lua` was hosted at `http://localhost:5000/fun.lua`, for example)?

**Comment by giann** [comment]
Yes you can redefine `package.path`.

**Comment by lukehedger** [comment]
Awesome - thanks @giann, that did the trick!

**Comment by SatishChandraPalakoti** [comment]
> Yes you can redefine `package.path`.

Can you shed more light on this ? I am banging my head around a similar issue since past 2 days and this seems like something similar to what I am experiencing.
