### ISSUE TITLE
require "b.lua" will be loaded twice

### ISSUE THREAD

**Issue by lovoror** [fengari-lua/fengari-web#35]
a.lua 
`
require b
`

b.lua will be loaded twice.please fixe it.

**Comment by giann** [comment]
Please provide a more context/code.

**Comment by lovoror** [comment]
test.lua
`print("load test lua file")`
script.lua
`require "test"`


The test.lua file will be loaded twice when you open the chrome developer tools.

**Comment by giann** [comment]
How do you load your files ?

If you have `<script>` tag for both file you don't need to require them.

**Comment by lovoror** [comment]
` luaWeb.run_lua_script_from_tag({
                     "src": "script.lua"
                 });`

**Comment by giann** [comment]
Do you have a `<script>` tag in your DOM ?

**Comment by lovoror** [comment]
yes

**Comment by daurnimator** [comment]
> ` luaWeb.run_lua_script_from_tag({ "src": "script.lua" });`

That is not a fengari function. Please try to replicate the issue using only fengari supported APIs.

**Comment by lovoror** [comment]
I export this function  "run_lua_script_from_tag()",because I need use this in js callback.
`dosomting(function(){
luaWeb.run_lua_script_from_tag({ "src": "script.lua" });
})`

**Comment by giann** [comment]
Your `script.lua` could return a function that you could then call from your callback

**Comment by daurnimator** [comment]
Closing due to lack of information.
