### ISSUE TITLE
Fengari+Phonegap: xhr.status is always 0

### ISSUE THREAD

**Issue by olueiro** [fengari-lua/fengari-web#38]
Hi
https://github.com/fengari-lua/fengari-web/blob/a9fb130f6851206e8a57be902af061e980be5610/src/fengari-web.js#L188

Reference: https://stackoverflow.com/q/33471547

**Comment by daurnimator** [comment]
From https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/status
> Before the request completes, the value of status is 0. Browsers also report a status of 0 in case of XMLHttpRequest errors.

This sounds like a bug in Phonegap.

**Comment by olueiro** [comment]
Hmm

I've created a [custom fengari(-web)](https://github.com/olueiro/fengari-phonegap-helloworld) version for PhoneGap with my modifications (xrs.status and error logging)

PS I've tested my package in local browser, Nox emulator and some mobile Android devices (no iOS :( ). In any tests, javascript `WeakMap` is undefined, so I have added a `WeakMap` polyfill

**Comment by daurnimator** [comment]
> I have added a `WeakMap` polyfill.

`Weakmap` is impossible to polyfill correctly (hence why it remains a hard dependency). 
Are you sure that your JS engine doesn't support `Weakmap`? If so it is very old and should be updated.

**Comment by olueiro** [comment]
I can reproduce this on Nox App player (latest version), running on Windows 10 machine. This sounds like a bug in Phonegap too. In my Android devices the JS engine supports WeakMap .

[This Map shim](https://github.com/eriwen/es6-map-shim/blob/master/es6-map-shim.js) emulates the Weakmap (`window.WeakMap = window.Map;`) and has solved my issue.

**Comment by daurnimator** [comment]
> window.WeakMap = window.Map;

that will end up leaking memory: the longer your page/app runs, the more memory it will use.
