### ISSUE TITLE
Fengari in rhino

### ISSUE THREAD

**Issue by ritzip** [fengari-lua/fengari-web#46]
is it possible to use fengari in sandboxed javascript? if so may i ask how?

**Comment by daurnimator** [comment]
> is it possible to use fengari in sandboxed javascript? if so may i ask how?

What do you mean sandboxed javascript?

**Comment by ritzip** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino

**Comment by daurnimator** [comment]
Rhino is just another javascript VM. Why is its sandbox unique to anything else?

**Comment by ritzip** [comment]
well, i have no idea how i would load it in pure javascript

**Comment by ritzip** [comment]
i also made this issue here because rhino does not support most es6 features and i'm sure to use -web

**Comment by daurnimator** [comment]
>  i'm sure to use -web

fengari-web is about running fengari in a web browser. If you're not in a web browser (which is what Rhino sounds like), then you likely should be using plain fengari + possibly fengari-interop.

> rhino does not support most es6 features

fengari should happily compile to ES5 by using babel or other translators.

**Comment by ritzip** [comment]
question, which scripts are necessary? i don't want to make another issue for this on the main repo so asking here

**Comment by daurnimator** [comment]
> question, which scripts are necessary?

necessary for *what*? each repository's readme explains what it does....

**Comment by ritzip** [comment]
~~lemme just..  dump everything into babel~~
