### ISSUE TITLE
Constructor Images requires "new"

### ISSUE THREAD

**Issue by DeybisMelendez** [fengari-lua/fengari-web#47]
I want to create an Image().

```
local myImage = js.global.Image()
```
With Javascript:

```
var myImage = new Image();
```

but it give me an error.
![Captura de pantalla_2020-08-14_19-28-03](https://user-images.githubusercontent.com/40205683/90302614-8eacb300-de64-11ea-9568-772014a3e50c.png)

uncaught exception TypeError: "Constructor Image requires 'new'"

    __call http://127.0.0.1:8080/js/fengari-web.js:8 t http://127.0.0.1:8080/js/fengari-web.js:8 t http://127.0.0.1:8080/js/fengari-web.js:8 luaV_execute http://127.0.0.1:8080/js/fengari-web.js:8 ut http://127.0.0.1:8080/js/fengari-web.js:8 ht http://127.0.0.1:8080/js/fengari-web.js:8 Ot http://127.0.0.1:8080/js/fengari-web.js:8 ot http://127.0.0.1:8080/js/fengari-web.js:8 vt http://127.0.0.1:8080/js/fengari-web.js:8 Rt http://127.0.0.1:8080/js/fengari-web.js:8 lua_pcall http://127.0.0.1:8080/js/fengari-web.js:8 w http://127.0.0.1:8080/js/fengari-web.js:8 C http://127.0.0.1:8080/js/fengari-web.js:8

**Comment by daurnimator** [comment]
Use `js.new(js.global.Image)`

**Comment by DeybisMelendez** [comment]
Thank you!!!!
