### ISSUE TITLE
Passing variables into Lua scripts

### ISSUE THREAD

**Issue by abeverley** [fengari-lua/fengari-web#48]
Sorry, this is a basic question, but I've spent hours on it!

What is the best way to call a Lua function from Javascript and pass variables into it? One option is maybe to use the global js variable, but this doesn't seem quite right. I found I could do it as below, but is this the best/recommended way?

```
    var L = fengari.L;
    var vars = {
        var1: 12,
        var2: 15
    };
    fengari.interop.push(L, vars);
    fengari.lua.lua_setglobal(L, "vars");

    // Better way to pass vars into this function?
    var ret = fengari.load('return vars.var1 + vars.var2')();
    console.log(ret);
```

I also tried returning a function from ```fengari.load``` but couldn't seem to find a way to call it from Javascript or pass in variables.

This issue here is similar but I couldn't see how to pass the values: https://github.com/fengari-lua/fengari-interop/issues/38

Any help/pointers would be appreciated. Many thanks.

**Comment by daurnimator** [comment]
```javascript
var ret = fengari.load('local vars = ...; return vars.var1 + vars.var2')(vars);
```

or 

```javascript
var func = fengari.load(`return function(var1, var2)
    return var1 + var2
end`)();
var ret = func.call(12, 15)
```

**Comment by abeverley** [comment]
Blimey, is it that easy, I must have tried all sorts of combinations like that :)

Many thanks for the quick reply.
