### ISSUE TITLE
Set FENGARICONF / lauconf for fengari-web

### ISSUE THREAD

**Issue by lorenzos** [fengari-lua/fengari-web#51]
Is it possible to set `FENGARICONF` (and so `lauconf`) when using `fengari-web`? I [see](https://github.com/fengari-lua/fengari-web/blob/master/webpack.config.js#L37) that `process.env.FENGARICONF` is forcefully set to void in [`webpack.config.js`](https://github.com/fengari-lua/fengari-web/blob/master/webpack.config.js), and in fact I wasn't able to set `conf` value by changing `process.env` when compiling my project, which has `fengari-web` as a dependency.

**Comment by daurnimator** [comment]
`FENGARICONF` should be thought of as a "compiletime" option; the distributed pre-compiled fengari-web has it hard-coded; but if you compile fengari-web yourself then you can modify it.

**Comment by daurnimator** [comment]
Closing as there are no action items here.
