### ISSUE TITLE
Fully compiled source template (with loader)?

### ISSUE THREAD

**Issue by reineimi** [fengari-lua/fengari-web#54]
Would be great if you've added it to the repository, since messing with npm and loader is such a nuisance.
 I'm trying to set it up on Windows since I do most of stuff on it, but none of mentioned things works adequately in there. So just downloading, and perhaps changing something here and there a little bit, would be a totally great option.
 It's just that I don't feel like dumping everything into either one HTML body or link Lua scripts through JS implementations; wouldn't it look terrible? Surely so.

**Comment by daurnimator** [comment]
Compiled source is attached to the releases. See https://github.com/fengari-lua/fengari-web/releases/tag/v0.1.4

We will not be committing compiled artifacts to the repository itself.
