### ISSUE TITLE
Question on handling promises.

### ISSUE THREAD

**Issue by Bat1963** [fengari-lua/fengari-web#55]
Dear Daurnimator, may I cross-post my question on reddit [about promises](https://www.reddit.com/r/lua/comments/x3mqkc/fengari_and_javascript_promises_question) ?

Any clues very much appreciated, thank you, Jon.C.

**Comment by daurnimator** [comment]
Looks like you figured it out. https://www.reddit.com/r/lua/comments/x3mqkc/comment/imx93tn/?utm_source=reddit&utm_medium=web2x&context=3
