### ISSUE TITLE
module not defined

### ISSUE THREAD

**Issue by ZultaCulu** [fengari-lua/fengari-web#56]
when i pull up the developer console, I get this error
Uncaught ReferenceError: module is not defined
    <anonymous> http://localhost:8000/Documents/GitHub/ZultaCulu.github.io/frameworks/fengari-web.js:1

**Comment by daurnimator** [comment]
We need far more information than this to debug; e.g. a full traceback, and what code were you trying to run?

**Comment by ZultaCulu** [comment]
> We need far more information than this to debug; e.g. a full traceback, and what code were you trying to run?

I was trying to run a simple hello world program.

**Comment by daurnimator** [comment]
> I was trying to run a simple hello world program.

How? Which hello world sample? via what mechanism? in which browser?

**Comment by ZultaCulu** [comment]
I tried doing a print("Hello World") both inside the index.html, and in an external file, in firefox and brave browser

**Comment by daurnimator** [comment]
That's not enough information for us to debug an issue.

**Comment by curious-broccoli** [comment]
I think that error happens when you try to load the `fengari-web.module.js`, rather than the `fengari-web.js` with a script tag
