### ISSUE TITLE
print() prints newlines instead of tabs/horizontal whitespace

### ISSUE THREAD

**Issue by RyanSquared** [fengari-lua/fengari-web#7]
`print(1, 2)` results in:

```
1
2
```

`print(1, 2, 3)` results in:

```
1
2
3
```

**Comment by TymurGubayev** [comment]
not "instead of spaces" but "instead of TABs" (at least that's how https://www.lua.org/cgi-bin/demo behaves)

**Comment by daurnimator** [comment]
What should the html end up as instead? At the moment the output from a `print` call is a `span` containing a `<pre>` element for each argument.

**Comment by giann** [comment]
We could style <pre> to be inlined

**Comment by daurnimator** [comment]
pre as `inline-block`? Still need to do "tab" seperation.
Perhaps a whole line should just be in one `pre`?

**Comment by daurnimator** [comment]
This should be moved to https://github.com/fengari-lua/fengari.io/issues
